config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'palindromes#input'

  get 'palindromes/input'
  get 'palindromes/view'

  get 'session/login'
  post 'session/create'
  get 'session/logout'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :old_password

  has_secure_password # validations: false

  validate :password_presence
  validate :correct_old_password, on: :update, if: -> { password.present? }
  validate :password_complexity

  validates :password, confirmation: { message: 'Пароли не совпадают.' },
                       allow_blank: true,
                       length: { minimum: 6, maximum: 70, message: 'Пароль слишком короткий,
                                                                   минимальная длина - 6 символов.' }

  validates :email, presence: { message: 'Пожалуйста, введите электронную почту.' },
                    uniqueness: { message: 'Пользователь с такой электронной почтой уже зарегистрирован.' },
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Введена некорректная электронная почта.' }
  # validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true
  validates :username, presence: { message: 'Пожалуйста, введите имя пользователя.' },
                       uniqueness: { message: 'Пользователь с таким именем уже зарегистрирован.' }

  def formatted_created_at
    created_at.strftime('%d.%m.%Y %T %Z')
  end

  def formated_last_login_at
    last_login_at.strftime('%d.%m.%Y %T %Z')
  end

  private

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'Введен неверный старый пароль.'
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])/

    errors.add :password, message: 'Пароль должнен содержать хотя бы: 1 прописную букву, 1 строчную букву и 1 цифру.'
  end

  def password_presence
    errors.add(:password, :blank) unless password_digest.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ErrorHandling
  include SessionHelper

  before_action :require_login
  before_action :update_last_login_at, if: lambda {
                                             user_signed_in? &&
                                               (current_user.last_login_at.nil? || current_user.last_login_at < 3.minutes.ago)
                                           }

  def update_last_login_at
    current_user.update_attribute(:last_login_at, Time.current)
  end

  private

  def require_login
    redirect_to session_login_url unless signed_in?
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?
end

app/controllers/concerns/error_handling.rb
# frozen_string_literal: true

module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/palindromes_controller.rb
# frozen_string_literal: true

class PalindromesController < ApplicationController
  def input; end

  def view
    @input = validate_input(params[:n])
    @numbers = (0..@input).select { |i| palindrome?(i * i) }
    @result = @numbers.size
  rescue StandardError => e
    @error = case e.class.to_s
             when 'ArgumentError' then 'Некорректный ввод. Используйте только цифры!'
             else e
             end
  end

  private

  def palindrome?(number)
    number.to_s == number.to_s.reverse
  end

  def validate_input(input)
    raise 'Вы ничего не ввели!' if input.empty?

    Integer(input)
  end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]
  before_action :require_login, only: %i[logout]

  def login; end

  def create
    user = User.find_by username: params[:username]

    # Метод authenticate автоматически добавляется с помощью has_secure_password.
    # Внутри себя он хэширует переданные ему параметры и сравнимавает это с
    # содержимым в базе данных.
    if user&.authenticate(params[:password])
      p 'LOGIN'
      sign_in user
      redirect_to root_path
    else
      p 'REDIRECT'
      flash[:danger] = 'Неверный логин и/или пароль'
      redirect_to session_login_path
    end
  end

  def logout
    sign_out
    redirect_to session_login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[new create]
  skip_forgery_protection

  # GET /users or /users.json
  def index
    @users = User.all
    @online_users = User.where('last_login_at > ?', 3.minutes.ago)
  end

  # GET /users/1 or /users/1.json
  def show
    @users = User.all
    @online_users = User.where('last_login_at > ?', 3.minutes.ago)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          flash[:success] = 'Параметры пользователя были успешно обновлены.'
          redirect_to @user
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :old_password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page
    css_class = current_page == title ? 'link-secondary' : 'link-dark'

    options[:class] = if options[:class]
                        "#{options[:class]} #{css_class}"
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: { current_page: current_page }
  end

  def full_title(page_title = '')
    base_title = 'Palindromes'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/palindromes_helper.rb
# frozen_string_literal: true

module PalindromesHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 2.days, http_only: true }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  # ||= означает, что если сurrent_user имеет значение nil,
  # то мы присваиваем ему значение, указанное ниже.
  # Если не nil, то мы присваиваем ему значение @current_user.
  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />

    <style>
    .main-container{
      margin-bottom: 70px;
    }
    </style>

  </head>

  <body>
    <%= yield :main_menu %>
    
    <main class="container main-container">

    <ul class="p-0">
      <% flash.each do |k, v| %>
          <%= tag.div v, class: "alert alert-#{k}", role: "alert" %>
      <% end %>
    </ul>

    <%= yield %>
      
    </main>
  </body>
</html>

app/views/palindromes/input.html.erb
<% provide :page_title, 'Ввод' %>
<% currently_at 'Главная' %>

<h1>Palindromes</h1><br/>
<p>     Определить количество неотрицательных целых чисел ≤ n (n
        вводится с клавиатуры), квадрат которых является палиндромом. Например:
        26^2 = 676.
</p>

<%= form_tag(palindromes_view_path, :method => "get") do %> 

    <%= label_tag :n, "Введите n: " %> 
    <%= text_field_tag :n, '', id: 'input_number', required: true %> <br/><br/>        <%#(:n, default_value)%>

    <%= button_tag "Найти палиндромы", type: 'submit', name: nil, id: 'btn_commit', class: 'btn btn-primary' %>
<% end %>

app/views/palindromes/view.html.erb
<% provide :page_title, 'Результат' %>
<% currently_at 'Главная' %>

<h1>Palindromes</h1><br/>

<% if @error %>
    <% flash[:danger] = @error %>
<% else %>
<div>Вы ввели: <%= @input %></div>
<div>Ответ: <%= @result %></div><br/>  
    <table class="table table-striped">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Число</th>
            <th scope="col">Квадрат числа</th>
        </tr>
        <% @numbers&.each_with_index do |numbers, i| %>
        <tr>
            <td scope="row"><%= i+1 %></td>
            <td scope="row"><%= numbers %></td>
            <td scope="row"><%= numbers * numbers %></td>
        </tr>
        <% end %>
    </table><br/>
<% end %>
<%= link_to "Вернуться", root_path %>

app/views/session/login.html.erb
<% provide :page_title, 'Вход' %>

<style>
  .container{
    padding-top: 70px;
  }
  .input-label{
    padding-bottom: 16px;
    font-family: var(--bs-font-sans-serif);
    /* color: #0d6efd; */
  }
</style>

<div class="container">

  <h1 class="text-center input-label">Вход</h1>

  <%= form_with url: session_create_url, class: 'col-4 d-flex flex-column justify-content-center m-auto', method: :post, local:true do |form| %>

    <div class="form-group pb-3 pt-10">
      <%= form.text_field :username, placeholder: 'Имя пользователя', class: 'form-control', required: true%>
    </div>

    <div class="form-group pb-3">
      <%= form.password_field :password, placeholder: 'Пароль', class: 'form-control', required: true%>
    </div>

    <div class="form-group pt-3 pb-3 text-center">
      <%= form.submit 'Войти', class: 'btn btn-primary' %>
    </div>

  <% end %>
  <p class="text-dark text-center pt-3">
        Еще нет профиля?
        <%= link_to 'Зарегистрируйтесь', new_user_path %>
  </p>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.values.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>  

  <div class="container">
    <header>
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
          <svg fill="#343434" xmlns="http://www.w3.org/2000/svg" width="100" viewBox="-59.385 -34.8 514.67 208.8">
            <path d="M344.6 121.1v18.1h32.7c6.7 0 18.2-4.9 18.6-18.6v-7c0-11.7-9.6-18.6-18.6-18.6H361v-8.4h32.3V68.4h-31c-8 0-18.7 6.6-18.7 18.9v6.3c0 12.3 10.6 18.6 18.7 18.6 22.5.1-5.4 0 15.4 0v8.8m-208.3-4.3s17.5-1.5 17.5-24.1-21.2-24.7-21.2-24.7h-38.2v71.3h19.2V122l16.6 17.2h28.4zm-7.4-14.6h-15.3V85.8h15.4s4.3 1.6 4.3 8.1-4.4 8.2-4.4 8.2zm72.3-33.7h-19.5c-13.9 0-18.6 12.6-18.6 18.6v52.2h19.5v-12.5H234v12.5h18.9V87c0-15.2-13.8-18.6-18.6-18.6zm-.3 38.1h-18.4V89.2s0-3.9 6.1-3.9h6.7c5.4 0 5.5 3.9 5.5 3.9v17.3zm27.8-38.1h20.3v70.8h-20.3zm28.6 0v70.8h47.5v-18.3h-27.3V68.4z"/>
            <path d="M7 139.2h79s-15.1-68.9 34.9-96.8c10.9-5.3 45.6-25.1 102.4 16.9 1.8-1.5 3.5-2.7 3.5-2.7s-52-51.9-109.9-46.1C87.8 13.1 52 39.6 31 74.6c-21 35-24 64.6-24 64.6z"/>
            <path d="M7 139.2h79s-15.1-68.9 34.9-96.8c10.9-5.3 45.6-25.1 102.4 16.9 1.8-1.5 3.5-2.7 3.5-2.7s-52-51.9-109.9-46.1C87.8 13.1 52 39.6 31 74.6c-21 35-24 64.6-24 64.6z"/>
            <path d="M7 139.2h79s-15.1-68.9 34.9-96.8c10.9-5.3 45.6-25.1 102.4 16.9 1.8-1.5 3.5-2.7 3.5-2.7s-52-51.9-109.9-46.1c-29.2 2.6-65 29.1-86 64.1-21 35-23.9 64.6-23.9 64.6zM171.6 16.1l.4-6.7c-.9-.5-3.4-1.7-9.7-3.5l-.4 6.6c3.3 1.1 6.5 2.3 9.7 3.6z"/>
            <path d="M162.1 37.3l-.4 6.3c3.3.1 6.6.5 9.9 1.2l.4-6.2c-3.4-.7-6.7-1.1-9.9-1.3zm-37-31.2h1l-2-6.1c-3.1 0-6.3.2-9.6.6l1.9 5.9c2.9-.3 5.8-.4 8.7-.4zm4.8 36.8l2.3 6.9c2.9-1.4 5.8-2.6 8.7-3.5l-2.2-6.6c-3.4 1-6.3 2.1-8.8 3.2zM84.5 16.6L80 9.7c-2.5 1.3-5.1 2.7-7.8 4.3l4.6 7c2.6-1.6 5.1-3.1 7.7-4.4zm20.5 45l4.8 7.2c1.7-2.5 3.7-4.8 5.9-7.1l-4.5-6.8c-2.3 2.1-4.4 4.4-6.2 6.7zM90.5 93.8l8.1 6.4c.4-3.9 1.1-7.8 2.1-11.7l-7.2-5.7c-1.3 3.7-2.2 7.4-3 11zM46.7 46.3l-7.1-6.2c-2.6 2.5-5.1 5-7.4 7.5l7.7 6.6c2.1-2.7 4.4-5.4 6.8-7.9zM16.5 91L5 86.8c-1.9 4.3-4 9.3-5 12l11.5 4.2c1.3-3.4 3.4-8.3 5-12zM89 119.2c.2 5.3.7 9.6 1.2 12.6l12 4.3c-.9-3.9-1.8-8.3-2.4-13z"/>
          </svg>
        </a>
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Главная', root_path,
            { class: 'nav-link px-2', current_page: current_page } %></li>
          <li><%= nav_tab 'Пользователи', users_path,
            { class: 'nav-link px-2', current_page: current_page } %></li>
        </ul>
        
        <div class="col-md-3 justify-content-end d-flex">
          <ul class="nav">
            <% if user_signed_in? %>
              <%# <button type="button" class="btn btn-outline-primary me-2" onClick='location.href="/session/logout"'>Выйти</button> %>
              <li class="dropdown" id="dropdownMenuLink">
                <%= nav_tab current_user.username, '#',
                    class: 'nav-link px-2 dropdown-toggle',
                    data: {'bs-toggle': 'dropdown'}, current_page: current_page %>
                
                <ul class="dropdown-menu text-end dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                  <li><%= link_to 'Профиль', current_user, class: 'dropdown-item' %></li>
                  <li><%= link_to 'Настройки', edit_user_path(current_user), class: 'dropdown-item' %></li>
                  <li class="dropdown-divider"></li>  
                  <li><%= link_to 'Выйти', session_logout_path, class: 'dropdown-item' %></li>
                </ul>

              </li>

            <% else %>
              <button type="button" class="btn btn-outline-primary me-2" onClick='location.href="/session/login"'>Войти</button>
              <button type="button" class="btn btn-primary", onClick='location.href="/users/new"'>Зарегистрироваться</button>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
  </div>
  
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user, class: 'col-4 form-settings' do |form| %>
  <div class="form-group pb-3 pt-10">
    <%= form.text_field :username, placeholder: 'Имя пользователя', class: 'form-control', required: true%>
  </div>

  <div class="form-group pb-3">
    <%= form.email_field :email, placeholder: 'name@example.com', class: 'form-control', required: true%>
  </div>

  <div class="form-group pb-3">
    <%= form.password_field :password, placeholder: 'Пароль', class: 'form-control', required: true%>
  </div>

  <div class="form-group pb-3">
    <%= form.password_field :password_confirmation, placeholder: 'Подтверждение пароля', class: 'form-control' %>
  </div>

  <% unless user.new_record? %>
    <div class="form-group pb-3">
      <%= form.password_field :old_password, placeholder: 'Старый пароль', class: 'form-control', required: true%>
    </div>
  <% end %>

  <div class="form-group pb-3 mt-3 form-button">
      <%= form.submit (user.new_record? ? 'Зарегистрироваться' : 'Сохранить'), class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/users/edit.html.erb
<% provide :page_title, 'Настройки' %>
<% currently_at current_user.username %>

<style>
  .registration-label{
    padding-bottom: 16px;
    font-family: var(--bs-font-sans-serif);
    /* color: #0d6efd; */
  }
</style>

<%= render 'shared/errors', object: @user %>

<h1 class="registration-label">Редактировать пользователя</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% provide :page_title, 'Пользователи' %>
<% currently_at 'Пользователи' %>

<h1>Пользователи</h1><br/>

<table class="w-100">
  <thead>
    <tr class="row">
      <th class="col-2">Имя пользователя</th>
      <th class="col-4">Хэшированный пароль</th>    <%# для того, чтобы убедиться, что пароль нельзя украсть %>
      <th class="col-2">Последний вход на сайт</th>
      <th class="col-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="row">
        <td class="col-2"><%= user.username %></td>
        <td class="col-4"><%= truncate user.password_digest, length: 45 %></td>
        <td class="col-2">
        <% if @online_users&.index(user) %>
          <span class="badge badge-pill alert-success">Online</span>
        <% else %>
          <% if user.last_login_at > 8.hours.ago %>
            <%= user.last_login_at.nil? ? "Never signed in" : time_ago_in_words(user.last_login_at) %> ago
          <% else %>
            <time datetime="<%= user.last_login_at unless user.last_login_at.nil? %>">
              <%= user.formated_last_login_at %>
            </time>
          <% end %>
        <% end %>
        </td>
        <td class="col-1"><%= link_to 'Посмотреть', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button onClick='location.href="/users/new"' type="button" class="btn btn-outline-primary me-2">Зарегистрировать пользователя</button>
<%# link_to 'Зарегистрировать пользователя', new_user_path %>

app/views/users/new.html.erb
<% provide :page_title, 'Регистрация' %>

<style>
  .container{
    padding-top: 70px;
  }
  .registration-label{
    padding-bottom: 16px;
    font-family: var(--bs-font-sans-serif);
    /* color: #0d6efd; */
  }
  .form-settings{
    display: flex;
    flex-direction: column;
    justify-content: center;
    margin: auto;
  }
  .form-button{
    text-align: center;
  }
</style>

<%= render 'shared/errors', object: @user %>

<div class="container">
  <h1 class="text-center registration-label">Регистрация</h1>

  <%= render 'form', user: @user %>

  <p class="text-dark text-center pt-3">
    Уже есть аккаунт?
    <a class="text-link" href="/session/login">Войдите</a>
  </p>
</div>

app/views/users/show.html.erb
<% provide :page_title, @user.username %>
<% currently_at @user.username %>

<style>
  .user-buttons{
    margin-top: 40px;
  }
</style>

<p id="notice"><%= notice %></p>

<h1><%= @user.username %></h1><br/>

<p>
  <strong>Имя пользователя:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Электронная почта:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Пользователь зарегистрирован:</strong>
  <time datetime="<%= @user.formatted_created_at %>">
    <%= @user.formatted_created_at %>
  </time>
</p>

<p>
  <strong>Последний вход на сайт:</strong>
  <% if @online_users&.index(@user) %>
    <span class="badge alert-success">Online</span>
  <% else %>
    <% if @user.last_login_at > 8.hours.ago %>
      <%= @user.last_login_at.nil? ? "Never signed in" : time_ago_in_words(@user.last_login_at) %> ago
    <% else %>
      <time datetime="<%= @user.last_login_at unless @user.last_login_at.nil? %>">
        <%= @user.formated_last_login_at %>
      </time>
    <% end %>
  <% end %>
</p>

<% if current_user == @user %>
  <div class="user-buttons">
    <%= link_to 'Редактировать', edit_user_path(@user), class: "btn btn-outline-primary me-3" %>
    <%= link_to 'Удалить аккаунт', @user, class: "btn btn-outline-danger me-2", method: :delete, data: { confirm: 'Вы уверены?' } %>
  </div>
<% end %>